stats_extraction_task:
  description: >
    Your task is to find out and make a list of the general statistics that are being talked about in the transcript.
    With General Statistics, I mean some kind of graph or chart or some kind of data that is being represented in a visual way.
    The statistics should be in the following format:
    - "text": Exact line from transcript where the particular statistic was mentioned.
    - "description": Brief description of the statistic to provide context.
    - "entities": Any associated entities like organization, companies, people or locations.

    If no statistics are mentioned in the transcript, return an empty JSON array: []

    Transcript:
    {topic} 

  expected_output: A list of Statistics with some details.
  agent: stats_extractor
